// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_TaskQuest();
Q_GHS_KEEP_REFERENCE(qml_register_types_TaskQuest)

class TaskQuestPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    TaskQuestPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_TaskQuest;
        Q_UNUSED(registration)
    }
};



#include "TaskQuestplugin_TaskQuestPlugin.moc"
